<<<<<<< HEAD
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package devwomen;

/**
 *
 * @author Rumeysa
 */
public class MainSponsor extends javax.swing.JFrame {

    /**
     * Creates new form MainSponsor
     */
    public MainSponsor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ButtonProfile = new javax.swing.JButton();
        ButtonAdvert = new javax.swing.JButton();
        ButtonReview1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ButtonProfile.setIcon(new javax.swing.ImageIcon("C:\\Users\\Rumeysa\\Downloads\\DevWomen_-main\\src\\assets\\sponsor_profile.png")); // NOI18N

        ButtonAdvert.setText("İLAN VER");
        ButtonAdvert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAdvertActionPerformed(evt);
            }
        });

        ButtonReview1.setText("İNCELE");
        ButtonReview1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonReview1ActionPerformed(evt);
            }
        });

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "\"İLAN 1 \"-\"ALAN\"-\"KONU\"-\"GİRİŞİMCİ \"", "\"İLAN 2 \"-\"ALAN\"-\"KONU\"-\"GİRİŞİMCİ \"", "\"İLAN 3 \"-\"ALAN\"-\"KONU\"-\"GİRİŞİMCİ \"", "\"İLAN 4 \"-\"ALAN\"-\"KONU\"-\"GİRİŞİMCİ \"", "\"İLAN 5 \"-\"ALAN\"-\"KONU\"-\"GİRİŞİMCİ \"", "\"İLAN 6 \"-\"ALAN\"-\"KONU\"-\"GİRİŞİMCİ \"", "\"İLAN 7 \"-\"ALAN\"-\"KONU\"-\"GİRİŞİMCİ \"", "\"İLAN 8 \"-\"ALAN\"-\"KONU\"-\"GİRİŞİMCİ \"", "\"İLAN 9 \"-\"ALAN\"-\"KONU\"-\"GİRİŞİMCİ \"", "\"İLAN 10 \"-\"ALAN\"-\"KONU\"-\"GİRİŞİMCİ \"", "\"İLAN 11 \"-\"ALAN\"-\"KONU\"-\"GİRİŞİMCİ \"", "\"İLAN 12 \"-\"ALAN\"-\"KONU\"-\"GİRİŞİMCİ \"", "\"İLAN 13 \"-\"ALAN\"-\"KONU\"-\"GİRİŞİMCİ \"", "\"İLAN 14 \"-\"ALAN\"-\"KONU\"-\"GİRİŞİMCİ \"", "\"İLAN 15 \"-\"ALAN\"-\"KONU\"-\"GİRİŞİMCİ \"", "\"İLAN 16 \"-\"ALAN\"-\"KONU\"-\"GİRİŞİMCİ \"", "\"İLAN 17 \"-\"ALAN\"-\"KONU\"-\"GİRİŞİMCİ \"", "\"İLAN 18 \"-\"ALAN\"-\"KONU\"-\"GİRİŞİMCİ \"" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jList1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(ButtonAdvert, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ButtonProfile)
                        .addGap(8, 8, 8))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(ButtonReview1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50))))
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 83, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ButtonAdvert, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonProfile))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(ButtonReview1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonAdvertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAdvertActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonAdvertActionPerformed

    private void ButtonReview1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonReview1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonReview1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainSponsor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainSponsor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainSponsor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainSponsor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainSponsor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonAdvert;
    private javax.swing.JButton ButtonProfile;
    private javax.swing.JButton ButtonReview1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
=======
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package devwomen;

/**
 *
 * @author Rumeysa
 */
public class MainSponsor extends javax.swing.JFrame {

    /**
     * Creates new form MainSponsor
     */
    public MainSponsor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ButtonProfile = new javax.swing.JButton();
        ButtonAdvert = new javax.swing.JButton();
        ButtonReview1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ButtonProfile.setIcon(new javax.swing.ImageIcon("C:\\Users\\Berfin\\Desktop\\DevWomen_\\DevWomen_\\src\\assets\\sponsor_profile.png")); // NOI18N

        ButtonAdvert.setText("İLAN VER");
        ButtonAdvert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAdvertActionPerformed(evt);
            }
        });

        ButtonReview1.setText("İNCELE");
        ButtonReview1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonReview1ActionPerformed(evt);
            }
        });

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "\"İLAN 1 \"-\"ALAN\"-\"KONU\"-\"GİRİŞİMCİ \"", "\"İLAN 2 \"-\"ALAN\"-\"KONU\"-\"GİRİŞİMCİ \"", "\"İLAN 3 \"-\"ALAN\"-\"KONU\"-\"GİRİŞİMCİ \"", "\"İLAN 4 \"-\"ALAN\"-\"KONU\"-\"GİRİŞİMCİ \"", "\"İLAN 5 \"-\"ALAN\"-\"KONU\"-\"GİRİŞİMCİ \"", "\"İLAN 6 \"-\"ALAN\"-\"KONU\"-\"GİRİŞİMCİ \"", "\"İLAN 7 \"-\"ALAN\"-\"KONU\"-\"GİRİŞİMCİ \"", "\"İLAN 8 \"-\"ALAN\"-\"KONU\"-\"GİRİŞİMCİ \"", "\"İLAN 9 \"-\"ALAN\"-\"KONU\"-\"GİRİŞİMCİ \"", "\"İLAN 10 \"-\"ALAN\"-\"KONU\"-\"GİRİŞİMCİ \"", "\"İLAN 11 \"-\"ALAN\"-\"KONU\"-\"GİRİŞİMCİ \"", "\"İLAN 12 \"-\"ALAN\"-\"KONU\"-\"GİRİŞİMCİ \"", "\"İLAN 13 \"-\"ALAN\"-\"KONU\"-\"GİRİŞİMCİ \"", "\"İLAN 14 \"-\"ALAN\"-\"KONU\"-\"GİRİŞİMCİ \"", "\"İLAN 15 \"-\"ALAN\"-\"KONU\"-\"GİRİŞİMCİ \"", "\"İLAN 16 \"-\"ALAN\"-\"KONU\"-\"GİRİŞİMCİ \"", "\"İLAN 17 \"-\"ALAN\"-\"KONU\"-\"GİRİŞİMCİ \"", "\"İLAN 18 \"-\"ALAN\"-\"KONU\"-\"GİRİŞİMCİ \"" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jList1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ButtonReview1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonAdvert, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(ButtonProfile)
                .addGap(14, 14, 14))
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(105, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ButtonProfile)
                    .addComponent(ButtonAdvert, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(85, 85, 85)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ButtonReview1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(99, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonAdvertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAdvertActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonAdvertActionPerformed

    private void ButtonReview1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonReview1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonReview1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainSponsor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainSponsor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainSponsor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainSponsor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainSponsor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonAdvert;
    private javax.swing.JButton ButtonProfile;
    private javax.swing.JButton ButtonReview1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
>>>>>>> b4ecd2cfa4fd571fa8586c2d4c6a90829b2b7643
